# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8881b633bea6706413eda6d9ae69f3eeabfd0d4796c5db1384f3c71f7ca2bb6cd2602991ec69f91725f7fa60ca35525426f8f8d85adcea21cc3d05c0509c8508

test:
  secret_key_base: 893a94e3849c701146aa258d4c86539d0a4e501a2ff4592099e0a30788cce7a42f763a8b114dc0e0e4d53c6e312aa4a0fda3d32500c0aad03f20de9de0a2f1a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
